spring:
  datasource:
    url: jdbc:h2:file:./target/h2db/db/policies;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    operationsSorter: method